### ISSUE TITLE
Build 12 is not supported with Bentobox 1.11.0

### ISSUE THREAD

**Issue by AmazedMender16** [BentoBoxWorld/Border#13]
You will receive a startup error:
`[16:10:15] [Server thread/WARN]: [BentoBox] Skipping Border as it is incompatible with the current version of BentoBox or of server software...
[16:10:15] [Server thread/WARN]: [BentoBox] NOTE: The addon is referring to no longer existing classes.
[16:10:15] [Server thread/WARN]: [BentoBox] NOTE: DO NOT report this as a bug from BentoBox.
[16:10:15] [Server thread/ERROR]: [BentoBox] Please report this stack trace to the addon's author(s): [tastybento] 
java.lang.NoClassDefFoundError: com/github/yannicklamprecht/worldborder/api/BorderAPI
	at world.bentobox.border.Border.onEnable(Border.java:73) ~[?:?]
	at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:177) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_232]
	at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:156) ~[?:?]
	at world.bentobox.bentobox.BentoBox.lambda$onEnable$2(BentoBox.java:177) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [Spigot-1.15.2:git-Spigot-800b93f-e911c70]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [Spigot-1.15.2:git-Spigot-800b93f-e911c70]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [Spigot-1.15.2:git-Spigot-800b93f-e911c70]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399) [Spigot-1.15.2:git-Spigot-800b93f-e911c70]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [Spigot-1.15.2:git-Spigot-800b93f-e911c70]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [Spigot-1.15.2:git-Spigot-800b93f-e911c70]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

Server: spigot 1.15.2

**Comment by tastybento** [comment]
Do you have the WorldBorderAPI plugin installed?

**Comment by AmazedMender16** [comment]
Uploaded it to the wrong directory.. sorry for the false alarm :)
