### ISSUE TITLE
Error and very lag when island reseting

### ISSUE THREAD

**Issue by SirvydasS** [BentoBoxWorld/Border#3]
#### Describe the bug

When player reseting island server (/is reset) TPS drops to 2 and about 10-15 sec is freeze.  

#### Steps to reproduce the behavior

Restart island with command /is reset

#### Expected behavior

NO LAG

#### Screenshots and videos (Optional)

```
[14:46:09 ERROR]: Could not pass event IslandDeleteEvent to BentoBox v1.10.0-SNAPSHOT-b1539
java.lang.IllegalArgumentException: UUID cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.15.1.jar:git-Paper-31]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.getOfflinePlayer(CraftServer.java:1422) ~[patched_1.15.1.jar:git-Paper-31]
        at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:820) ~[patched_1.15.1.jar:git-Paper-31]
        at world.bentobox.border.listeners.PlayerListener.onIslandExitEvent(PlayerListener.java:57) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor495.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-31]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-31]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-31]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-31]
        at world.bentobox.bentobox.api.events.island.IslandEvent$IslandEventBuilder.build(IslandEvent.java:464) ~[?:?]
        at world.bentobox.bentobox.managers.IslandsManager.deleteIsland(IslandsManager.java:302) ~[?:?]
        at world.bentobox.bentobox.managers.island.NewIsland.lambda$newIsland$0(NewIsland.java:258) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-31]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-31]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-31]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-31]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-31]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-31]
        at java.lang.Thread.run(Thread.java:835) [?:?]
```

##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.1.
BentoBox version: 1.10.0-SNAPSHOT-b1539
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.6.0.1-SNAPSHOT-b149 (ENABLED)
Border 1.0.2 (ENABLED)
BSkyBlock 1.10.0-SNAPSHOT-b563 (ENABLED)
Challenges 0.9.0-SNAPSHOT-#395 (ENABLED)
DimensionalTrees 1.6.0-SNAPSHOT-b78 (ENABLED)
Greenhouses 1.0.0 (ENABLED)
Level 1.9.1-SNAPSHOT-b331 (ENABLED)
Likes 1.7.0-SNAPSHOT-#14 (ENABLED)
Limits 1.9.0 (ENABLED)
MagicCobblestoneGenerator 1.9.0-SNAPSHOT-b92 (ENABLED)
TwerkingForTrees 1.1.2 (ENABLED)
Warps 1.9.2-SNAPSHOT-b217 (ENABLED)

```

**Comment by tastybento** [comment]
Thanks. Fixed.
