### ISSUE TITLE
Island Border broken with error

### ISSUE THREAD

**Issue by daoshii** [BentoBoxWorld/Border#32]
### Description
Error upon entering server, entering island, and exiting island. Worldborder does not show. I have deleted database and worlds upon updating to Paper 1.16 just to be sure. I have the latest Worldborder API. I set a worldborder in spawn just to test and make sure the plugin was working and it does fully work, Just not on islands.
#### Describe the bug
Multiple errors, and worldborder does not show.

#### Expected behavior
The border should show

##### Output of `/bbox version` (Mandatory)
```
[02:36:54 INFO]: Running PAPER 1.16.1.
[02:36:54 INFO]: BentoBox version: 1.14.0-SNAPSHOT-b1819
[02:36:54 INFO]: Database: JSON
[02:36:54 INFO]: Loaded Game Worlds:
[02:36:54 INFO]: sblock (sblock): Overworld, Nether*, The End*
[02:36:54 INFO]: Loaded Addons:
[02:36:54 INFO]: Biomes 1.13.0-SNAPSHOT-b167 (ENABLED)
[02:36:54 INFO]: Border 1.0.8-SNAPSHOT-b28 (ENABLED)
[02:36:54 INFO]: BSkyBlock 1.14.0-SNAPSHOT-b655 (ENABLED)
[02:36:54 INFO]: ControlPanel 1.13.0-SNAPSHOT-b22 (ENABLED)
[02:36:54 INFO]: Level 2.1.0-SNAPSHOT-b365 (ENABLED)
[02:36:54 INFO]: Limits 1.14.0-SNAPSHOT-b222 (ENABLED)
[02:36:54 INFO]: MagicCobblestoneGenerator 1.9.1-SNAPSHOT-b108 (ENABLED)
[02:36:54 INFO]: Upgrades 0.1.0-SNAPSHOT-b37 (ENABLED)
[02:36:54 INFO]: Warps 1.9.8-SNAPSHOT-b248 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (14): BentoBox, CMI, CMIPaperLib, DragonSlayer, LuckPerms, MMOItems, MMOLib, MythicMobs, SilkSpawners, Vault, VoidSpawn, WorldBorderAPI, WorldEdit, WorldGuard
```
###The Error
https://pastebin.com/pgYVu1YB
```
[02:26:46 ERROR]: Could not pass event PlayerJoinEvent to BentoBox v1.14.0-SNAPSHOT-b1819
java.lang.IncompatibleClassChangeError: Found interface com.github.yannicklamprecht.worldborder.api.WorldBorderApi, but class was expected
at world.bentobox.border.Border.removeBorder(Border.java:68) ~[?:?]
at world.bentobox.border.Border.updateBorder(Border.java:57) ~[?:?]
at world.bentobox.border.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:37) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor739.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-2]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PlayerList.postChunkLoadJoin(PlayerList.java:266) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PlayerList.lambda$null$1(PlayerList.java:213) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:373) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-2]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[02:26:46 INFO]: TheRealDaoshi joined the game
[02:26:47 INFO]: TheRealDaoshi[/73.211.248.44:49914] logged in with entity id 479 at ([world]16.170547547054653, 86.0, -106.70162386788392)
[02:30:05 INFO]: TheRealDaoshi issued server command: /is home


[02:30:08 INFO]: TheRealDaoshi issued server command: /is
[02:30:10 ERROR]: Could not pass event IslandEnterEvent to BentoBox v1.14.0-SNAPSHOT-b1819
java.lang.IncompatibleClassChangeError: Found interface com.github.yannicklamprecht.worldborder.api.WorldBorderApi, but class was expected
at world.bentobox.border.Border.removeBorder(Border.java:68) ~[?:?]
at world.bentobox.border.Border.updateBorder(Border.java:57) ~[?:?]
at world.bentobox.border.listeners.PlayerListener.onIslandEnterEvent(PlayerListener.java:56) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor746.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-2]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-2]
at world.bentobox.bentobox.api.events.island.IslandEvent$IslandEventBuilder.build(IslandEvent.java:706) ~[?:?]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.lambda$handleEnterExit$1(EnterExitListener.java:82) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.handleEnterExit(EnterExitListener.java:74) ~[?:?]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.onTeleport(EnterExitListener.java:35) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor95.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-2]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:779) ~[patched_1.16.1.jar:git-Paper-2]
at world.bentobox.bentobox.paperlib.features.asyncteleport.AsyncTeleportPaper.lambda$teleportAsync$0(AsyncTeleportPaper.java:16) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996) ~[?:1.8.0_242]
at world.bentobox.bentobox.paperlib.features.asyncteleport.AsyncTeleportPaper.teleportAsync(AsyncTeleportPaper.java:16) ~[?:?]
at world.bentobox.bentobox.paperlib.environments.Environment.teleport(Environment.java:79) ~[?:?]
at world.bentobox.bentobox.paperlib.PaperLib.teleportAsync(PaperLib.java:74) ~[?:?]
at world.bentobox.bentobox.managers.IslandsManager.lambda$homeTeleportAsync$7(IslandsManager.java:848) ~[?:?]
at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) ~[?:1.8.0_242]
at world.bentobox.bentobox.managers.IslandsManager.homeTeleportAsync(IslandsManager.java:832) ~[?:?]
at world.bentobox.bentobox.managers.IslandsManager.homeTeleportAsync(IslandsManager.java:811) ~[?:?]
at world.bentobox.bentobox.managers.island.NewIsland.lambda$newIsland$1(NewIsland.java:239) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-2]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]


[02:30:11 WARN]: [BentoBox] Task #7745 for BentoBox v1.14.0-SNAPSHOT-b1819 generated an exception
java.lang.IncompatibleClassChangeError: Found interface com.github.yannicklamprecht.worldborder.api.WorldBorderApi, but class was expected
at world.bentobox.border.Border.removeBorder(Border.java:68) ~[?:?]
at world.bentobox.border.Border.updateBorder(Border.java:57) ~[?:?]
at world.bentobox.border.listeners.PlayerListener.lambda$onPlayerTeleport$1(PlayerListener.java:61) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-2]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]


[02:30:30 ERROR]: Could not pass event IslandExitEvent to BentoBox v1.14.0-SNAPSHOT-b1819
java.lang.IncompatibleClassChangeError: Found interface com.github.yannicklamprecht.worldborder.api.WorldBorderApi, but class was expected
at world.bentobox.border.Border.removeBorder(Border.java:68) ~[?:?]
at world.bentobox.border.listeners.PlayerListener.onIslandExitEvent(PlayerListener.java:70) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor744.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-2]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-2]
at world.bentobox.bentobox.api.events.island.IslandEvent$IslandEventBuilder.build(IslandEvent.java:710) ~[?:?]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.lambda$handleEnterExit$0(EnterExitListener.java:69) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.handleEnterExit(EnterExitListener.java:61) ~[?:?]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.onMove(EnterExitListener.java:30) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor96.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-2]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1163) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-2]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]


[02:30:38 ERROR]: Could not pass event IslandEnterEvent to BentoBox v1.14.0-SNAPSHOT-b1819
java.lang.IncompatibleClassChangeError: Found interface com.github.yannicklamprecht.worldborder.api.WorldBorderApi, but class was expected
at world.bentobox.border.Border.removeBorder(Border.java:68) ~[?:?]
at world.bentobox.border.Border.updateBorder(Border.java:57) ~[?:?]
at world.bentobox.border.listeners.PlayerListener.onIslandEnterEvent(PlayerListener.java:56) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor746.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-2]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-2]
at world.bentobox.bentobox.api.events.island.IslandEvent$IslandEventBuilder.build(IslandEvent.java:706) ~[?:?]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.lambda$handleEnterExit$1(EnterExitListener.java:82) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.handleEnterExit(EnterExitListener.java:74) ~[?:?]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.onMove(EnterExitListener.java:30) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor96.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-2]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1163) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-2]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]


[02:34:08 INFO]: TheRealDaoshi issued server command: /spawn
[02:34:08 ERROR]: Could not pass event IslandExitEvent to BentoBox v1.14.0-SNAPSHOT-b1819
java.lang.IncompatibleClassChangeError: Found interface com.github.yannicklamprecht.worldborder.api.WorldBorderApi, but class was expected
at world.bentobox.border.Border.removeBorder(Border.java:68) ~[?:?]
at world.bentobox.border.listeners.PlayerListener.onIslandExitEvent(PlayerListener.java:70) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor744.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-2]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-2]
at world.bentobox.bentobox.api.events.island.IslandEvent$IslandEventBuilder.build(IslandEvent.java:710) ~[?:?]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.lambda$handleEnterExit$0(EnterExitListener.java:69) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_242]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.handleEnterExit(EnterExitListener.java:61) ~[?:?]
at world.bentobox.bentobox.listeners.flags.worldsettings.EnterExitListener.onTeleport(EnterExitListener.java:35) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor95.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-2]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:779) ~[patched_1.16.1.jar:git-Paper-2]
at io.papermc.lib.features.asyncteleport.AsyncTeleportPaper.lambda$teleportAsync$0(AsyncTeleportPaper.java:16) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628) ~[?:1.8.0_242]
at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996) ~[?:1.8.0_242]
at io.papermc.lib.features.asyncteleport.AsyncTeleportPaper.teleportAsync(AsyncTeleportPaper.java:16) ~[?:?]
at io.papermc.lib.environments.Environment.teleport(Environment.java:79) ~[?:?]
at io.papermc.lib.PaperLib.teleportAsync(PaperLib.java:86) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.finalizeTeleport(Teleportations.java:693) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:419) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:363) ~[?:?]
at com.Zrips.CMI.commands.list.spawn.perform(spawn.java:47) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-2]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]


[02:34:08 WARN]: [BentoBox] Task #11055 for BentoBox v1.14.0-SNAPSHOT-b1819 generated an exception
java.lang.IncompatibleClassChangeError: Found interface com.github.yannicklamprecht.worldborder.api.WorldBorderApi, but class was expected
at world.bentobox.border.Border.removeBorder(Border.java:68) ~[?:?]
at world.bentobox.border.Border.updateBorder(Border.java:57) ~[?:?]
at world.bentobox.border.listeners.PlayerListener.lambda$onPlayerTeleport$1(PlayerListener.java:61) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-2]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-2]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-2]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by tastybento** [comment]
#31 Duplicate
